### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by lulco** [mnapoli/bref#10]
Hi, can anybody help me with setup of AWS? Probably some permissions problem.
I know this is not exactly issue for bref, but maybe someone can help.
I am trying to execute example hello world code from readme. Code was successfully uploaded, but I get this Error:

```
{
  "errorMessage": "RequestId: 5132a39e-662b-11e8-bd86-f374b2af9362 Process exited before completing request"
}

START RequestId: 5132a39e-662b-11e8-bd86-f374b2af9362 Version: $LATEST
2018-06-02T06:08:06.724Z	5132a39e-662b-11e8-bd86-f374b2af9362	Error: spawn EACCES
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:378:9)
    at exports.handle (/var/task/handler.js:32:18)
END RequestId: 5132a39e-662b-11e8-bd86-f374b2af9362
REPORT RequestId: 5132a39e-662b-11e8-bd86-f374b2af9362	Duration: 71.31 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 19 MB	
RequestId: 5132a39e-662b-11e8-bd86-f374b2af9362 Process exited before completing request
```

Line 32: `let script = spawn('php', ['bref.php', JSON.stringify(event)]);`

**Comment by mnapoli** [comment]
I have been looking around at what `spawn EACCES` means and it seems it's a permission issue. So if I understand correctly, NodeJS cannot execute `php` because of permission issues?

That seems to be a problem with Bref. Maybe when the `php` binary is downloaded on your machine (when the lambda is being built) your system puts the wrong permissions on this file?

Which OS are you using to deploy?

Can you run `ls -l .bref/output/.bref/bin` in your directory project and paste the output here. That will tell us the permissions of the PHP binary that was uploaded.

**Comment by lulco** [comment]
Deploy is running on Ubuntu under vagrant hosted on Windows 7 machine O:-)

```
$ ls -la
total 41960
drwxrwxr-x 2 vagrant www-data     4096 jún  2 11:11 ./
drwxrwxr-x 3 vagrant www-data     4096 jún  1 16:30 ../
-rwxrwxr-- 1 vagrant www-data 42956336 jún  2 11:11 php*
```

After changing to 777 I deployed application again and it works now. Thanks! I spent lot of time with setting permissions on AWS, but I didn't see on my own environment :)

**Comment by mnapoli** [comment]
Thanks, please try version `0.2.11` and let me know if it's alright!
