### ISSUE TITLE
getting spawn E2BIG error

### ISSUE THREAD

**Issue by omygod9138** [mnapoli/bref#148]
I'm using Bref on aws Lambda to handle webhook requests.
It worked fine for the first two days. but on the third day I started to get

> Error: spawn E2BIG
at _errnoException (util.js:1022:11)
at ChildProcess.spawn (internal/child_process.js:323:11)
at exports.spawn (child_process.js:502:9)
at exports.handle (/var/task/handler.js:39:18)

I google for the meaning of spawn E2BIG and the answer I got is Argument list too long
so I assumed it is caused by event JSON is too long to pass from node js to php

![selection_044](https://user-images.githubusercontent.com/11039161/50959412-de473200-14fd-11e9-82e6-7b34dfa1aea8.png)

I would've tried to look at what was causing the JSON event too long, but I can't modify handler.js.
Is there any work around for this?

**Comment by mnapoli** [comment]
Hi, you may be right about the source of the bug.

To be transparent with you, most of the effort is spent on the new [0.3 version](#113) which will (very probably) solve that problem because it won't use JavaScript anymore. The new version will take advantage of the official runtime API, so the event will be fetched directly by PHP.

**Comment by omygod9138** [comment]
Nice! look forward to it!

In the meantime, is there any direction you can point out to me so that I can have a quick fix on my own?

**Comment by mnapoli** [comment]
Closing since this is fixed in 0.3.
