### ISSUE TITLE
Symfony v2.8.49 support

### ISSUE THREAD

**Issue by ThunderBoltEngineer** [mnapoli/bref#180]
It seems like this package only supports Symfony version higher than v3.0.0.  (throwing error messages when I try `composer require mnapoli/bref`)

But our current project is based on v2.8.49 and it is hard to upgrade the dependency.

Could you let me know if we can resolve this issue in a quick way?  Or must upgrade the framework version to 3+?

It would be really great if you can provide any solution to resolve this issue without touching the existing dependencies.

**Comment by nealio82** [comment]
I was discussing Bref with @xabbuh (SF core team member) a few momths ago and mentioned that I'd tried with SF 2.8 but had some trouble getting it running (2.4 & 4.x worked just fine). He told me he was skeptical that it would work with Bref's current incarnation because of a number of potential pitfalls baked into SF 2.8. With that in mind, I didn't bother trying too hard getting 2.8 to work, especially as 2.8 is now EOL and unsupported.

However... With the recent changes to the way Lambda handles external runtimes and the cleanup that allows us to do throughout the code, I think it's quite likely that SF 2.8 might just happen to start working out of the box. We're working hard on implementing the new Lambda runtime changes in Bref's `0.3` branch, but things are still experimental and under heavy development right now.

**Comment by mnapoli** [comment]
+1 the 0.3 version (see #116) works with PHP-FPM so it should support Symfony 2.8.

However it might also be a problem with the dependencies in `composer.json`. The goal would be to reduce Bref's dependencies as much as possible, and those left we could maybe try to require `2.8|3.*|4.*`?

**Comment by ThunderBoltEngineer** [comment]
Thanks for your support 👍
