### ISSUE TITLE
Support for other FaaS (Google, IBM, etc.)

### ISSUE THREAD

**Issue by akondas** [mnapoli/bref#235]
Hey, what about other vendors that offering FaaS (Google, IBM, etc.). I've already read the topic: #99 but it does not follow clearly whether the support of other vendors will be abandoned.

**Comment by mnapoli** [comment]
Hi, yes AWS is the only provider supported by Bref and it is the only one planned to be supported at the moment.

The reasons for this come from one of the principle behind bref (see https://bref.sh/docs/):

> **simplify problems by removing choices** instead of trying to address every need

Providing compatibility with multiple providers would be a lot of work for maintainers, and would be more work as well for users. Indeed that would raise the question of which one to use? On top of that the experience is different from provider to provider, for example there can be important performance differences. It could be deceiving for users (that could expect the same experience between providers).

Now why AWS and not another one?

> The choice of AWS as serverless provider is deliberate: at the moment AWS is the leading hosting provider, it is ahead in the serverless space in terms of features, performances and reliability.

Now this decision is made based on the current situation. If the situation changes (and it will very probably change over time) we should definitely revisit this.

But TL/DR Bref's choices could be summed up like this: **it is more important to provide one good solution than many poor solutions.**

**Comment by akondas** [comment]
Thanks for the comprehensive explanation :+1:

**Comment by fgilio** [comment]
I'd love to be able to use Bref with Google Cloud Functions. But, to be fair, it's currently miles behind AWS Lambda... I really hope that changes soon rather than later.

**Comment by InstanceOfMichael** [comment]
How is google cloud functions miles behind AWS Lambda?

**Comment by fgilio** [comment]
It has better performance, has the 3G of RAM option, can be set to run for up to 15 minutes, you have API gateway to "easily" setup a domain, the ecosystem is richer in terms of other AWS services that integrate with Lambda and there's also much more stuff built/written by the community. These are the ones that come to my mind right now, and will depend on the use case.

That said, I'm using Cloud Functions because of free credits and I'm happy with it. But I'm 99% sure I'd choose Lambda.

Nice post, thanks for sharing it. Cloud Run is indeed a really good option in some cases.

**Comment by InstanceOfMichael** [comment]
If Fargate could scale to zero, it might be equivalent.

**Comment by deleugpn** [comment]
Fargate can scale to 0 for asynchronous workloads.
