### ISSUE TITLE
$_ENV not available on Console

### ISSUE THREAD

**Issue by deleugpn** [mnapoli/bref#241]
I'm not sure if it's related to https://github.com/mnapoli/bref/issues/116#issuecomment-453740463 but I'm currently having this problem with the `console` layer.

Stack
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Name:
    Type: String
    AllowedPattern: '[a-z-].+'

Globals:
  Function:
    Environment:
      Variables:
        APP_SERVICES_CACHE: '/tmp/cache/services.php'
        APP_PACKAGES_CACHE: '/tmp/cache/packages.php'
        APP_ROUTES_CACHE: '/tmp/cache/routes.php'

Resources:
  Synchronizer:
    Type: AWS::Serverless::Function
    Properties:
      Role: !ImportValue LambdaExecutionRoleArn
      CodeUri: .
      Handler: artisan
      Timeout: 300
      MemorySize: 1024
      Runtime: provided
      Layers:
        - arn:aws:lambda:eu-west-1:209497400698:layer:php-72:1
        - arn:aws:lambda:eu-west-1:209497400698:layer:console:1
      VpcConfig:
        SecurityGroupIds: [!ImportValue AllowAllAddressesContainerSecurityGroup]
        SubnetIds: !Split [',', !ImportValue PrivateSubnets]
```

I changed the `artisan` file to look like this 

```
#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

print_r($_ENV);
exit;
```

When running the Test execution from Console, the output is basically an empty array.

```
{
  "exitCode": 0,
  "output": "Array\n(\n)"
}
```

I was trying to take advantage of https://github.com/laravel/framework/pull/27389, but doesn't seem like it's working, not sure if it's because of the layer.

**Comment by mnapoli** [comment]
The comment you linked to was because PHP-FPM has a specific config to forward environment variables to sub-processes (by default it doesn't).

Here the console layer using `exec()` to run the script (see https://github.com/mnapoli/bref/blob/master/runtime/console/bootstrap#L29). AFAIK exec does not reset the environment variables.

What you could do is create the `bootstrap` file in your project (copy the content of the console's `bootstrap` file I linked above). Then you can dump `$_ENV` in there and see if it's empty?

Also I think I remember issues between using `$_ENV` and `getenv()` or `$_SERVER` (I think I read that in Symfony's code). Could you try with those 2 other techniques see if the variable appears?

**Comment by mnapoli** [comment]
Closing until the bug is validated.
