### ISSUE TITLE
Deploy Laravel app size too big?

### ISSUE THREAD

**Issue by viezel** [mnapoli/bref#254]
I have an almost vanilla laravel app that I want to deploy with Bref. But I get the following when I run `sam deploy ...`

CREATE_FAILED | AWS::Lambda::Function
**Unzipped size must be smaller than 156807909 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException**

How do you overcome this challenge?

**Comment by viezel** [comment]
arh, good old `node_modules`.

**Comment by nealio82** [comment]
I assume you're deploying from your local dev machine? If you're deploying from CI you generally don't have this problem because all you do is clone your code, run `composer install --no-dev`, and then package & deploy.

If you're deploying from local you need to remove `node_modules/`, get rid of `.git/` and `.idea/`, etc...

For me the easiest solution has been to create a 'deploy' directory outside of the project and add a `deploy.sh` script inside it containing something like the following:

```
|- project-working-directory
   |- node_modules/
   |- src/
   | - vendor/
|- deploy-directory
   |- deploy.sh
```

```
cp -Rf ../<project-working-directory>/* . && rm -rf var/cache/* && rm -rf node_modules && composer install --optimize-autoloader --no-dev && php bin/console cache:warmup --env=prod  && sam package --output-template-file .stack.yaml --s3-bucket <s3-bucket-name> && sam deploy --template-file .stack.yaml --stack-name <app-stack-name> --capabilities CAPABILITY_IAM
```

This simply copies everything (except anything preceded with a `.`) across, removes `node_modules`, runs `composer install` while optimising the autoloader and ignoring dev dependencies, warms the cache (I'm using Symfony) to avoid it needing to be done on the first request, and goes through the rest of the deployment steps.

**Comment by nealio82** [comment]
Oddly, AWS documentation says the deployment package must be < `250 MB` (https://docs.aws.amazon.com/lambda/latest/dg/limits.html), but `156807909 B` is only `156 MB`.

**Comment by mnapoli** [comment]
Could it be because of the layer size? 94Mb still sounds like a lot for the layer 🤔

**Comment by nealio82** [comment]
Oh, I didn't consider that the layer wasn't taken into account with the reported size in the error message - I presumed that it was reporting the total size. Makes sense though!

**Comment by JGamboa** [comment]
So how to do it?

**Comment by viezel** [comment]
@JGamboa my solution was to remove `node_modules` and run `composer install --no-dev` to remove all unnecessary code. 
if your source code is still above the size limit, then I would reconsider if that the right kind of project to put into serverless to time being. Meaning, typically we want to keep lambda functions as lightweight as possible. 

I played with Laravel for serverless for some time, but found its actually much more beneficial to reconsider the code structure into small projects with much less code.

**Comment by nealio82** [comment]
@JGamboa did you follow this https://github.com/brefphp/bref/issues/254#issuecomment-469025023? what have you tried so far?

**Comment by guizmo51** [comment]
Hey i got the same issue I checked... "node_modules" was in the "ignore" part of the serverless config file , the "vendor" directory wasn't too big. In fact after an other check it was the var/cache folder...
