### ISSUE TITLE
How to access headers?

### ISSUE THREAD

**Issue by summersab** [mnapoli/bref#270]
I've been Googling and reading docs all day, and I'm clearly misunderstanding something simple. I've deployed a simple function using Bref - nothing special:
```
<?php
echo '<pre>' . print_r(get_defined_vars(),1) . '</pre>';
?>
```

My `template.yaml` is basically all defaults - I've just adjusted the handler and path values.

On my local system, I'm using the `$_SERVER['HTTP_REFERER']` variable in a certain script. Well . . . that doesn't exist in Lambda. How do I access/pass the HTTP headers to my function?

**Comment by mnapoli** [comment]
A bit of context could help, can you confirm:

- that you create a **HTTP** lambda?
- that you can send a HTTP response in your script and it works?
- that you can access for example `$_GET['name']` if you add a `?name=Bob` to your URL?

The issue is "how to access headers", but this is the same as in any other PHP application.

Maybe you are looking specifically for `HTTP_REFERER` and this key is missing?

But I need to know if the problem is that only `HTTP_REFERER` is missing, or if it's a global issue.

**Comment by summersab** [comment]
> The issue is "how to access headers": the answer is "just like usual in PHP".

Ugh . . . you provided me with a path to answering my own question. I'm so used to being on a LAMP stack that it didn't occur to me to use one of the other PHP-native functions to get headers instead of relying on superglobals like `$_SERVER`. (Actually . . . I've only EVER been on a LAMP stack, so I didn't know that there were other ways to do it). Doing a quick `getallheaders()` solved the problem.

Sorry to open an issue, but I was totally at my wit's end. Thanks!
