### ISSUE TITLE
mysqli support?

### ISSUE THREAD

**Issue by kaihendry** [mnapoli/bref#294]
I have some code that accesses RDS via IAM.

     $mysqli->real_connect($clusterEndpoint, $dbUsername, $token, $dbDatabase, $clusterPort, NULL, MYSQLI_CLIENT_SSL);

I'm puzzled how to get this working within a bref environment.

I previously had it working via `RUN docker-php-ext-install mysqli` in my Dockerfile.

**Comment by nealio82** [comment]
You can clone the Bref repo and use the `runtime/publish.php` script in there to create your own layers. You'll need to add `--enable-mysqli` to `runtime/php/php.Dockerfile` first, but that will then create your own PHP layer with `mysqli` installed and enabled.

Before you run the `publish` script it's worth going through removing any regions and PHP versions you don't want, otherwise Docker is going to be spinning your fans for ages!

(trust me, we know we need to document how to do this!)

**Comment by kaihendry** [comment]
Thank you, it worked. The build alarmingly took ages though.

Be good if mysqli was part of your distro. I'm a little surprised mysql-pdo is preferred.

**Comment by mnapoli** [comment]
@kaihendry new runtimes include mysqli by default!
