### ISSUE TITLE
Clean empty output

### ISSUE THREAD

**Issue by t-geindre** [mnapoli/bref#33]
Here:

https://github.com/mnapoli/bref/blob/e90ca4f207e773aa600e3e0ade6143bef65be9ef/src/Application.php#L140-L142

If the handler doesn't return any output, the `null` value will be json encoded, resulting in `null` string. I think it's a strange behavior. The output should be empty if the handler just return `null`.

**Comment by mnapoli** [comment]
After digging into this I don't think there is a problem here. The output is JSON-serialized in PHP in order to pass it back to `handler.js`.

But `handler.js` decodes the JSON to return the object/array/null to AWS lambda:

https://github.com/mnapoli/bref/blob/442f20dce5feb3bcbe7ec075ea5903b3720cf6bd/template/handler.js#L44-L53

So in the end, the `"null"` string that PHP encoded will be returned as a `null` value to AWS lambda by `handler.js`. All is good. (and if we make an exception here then `JSON.parse()` in `handler.js` will fail reading the JSON)

I'll close this, let me know if you think I'm mistaken.
