### ISSUE TITLE
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions

### ISSUE THREAD

**Issue by feoktistovroman** [mnapoli/bref#331]
The runtime parameter of nodejs6.10 is no longer supported for creating or updating AWS Lambda functions

**Comment by wysow** [comment]
@feoktistovroman You just have to update to `nodejs8.10` and it should be fine, already tested.

**Comment by nealio82** [comment]
Bref hasn't used the nodejs runtime since version `0.2` (late 2018), and since `0.3` has used layers and the Lambda runtime API instead. This gives us / you much greater support and flexibility.

Is there a reason why you need to continue using the `0.2` branch instead of the current master?

@mnapoli is it worth bumping the nodejs version in `0.2`?

**Comment by mnapoli** [comment]
I don't think it's worth updating the older 0.2 version as it's outdated (let's focus the effort on the current version), and the change to apply is straightforward.

Please let me know if I missed anything, I like to close issues when they seemed to be "addressed" to keep the issue tracker up to date :)
